import type { FreebuffSessionServerResponse } from '@codebuff/common/types/freebuff-session'

export type FreeSessionStatus = 'queued' | 'active'

/** Public state returned to CLI clients. Excludes `status: 'none'`, which is
 *  generated by the route handler when `getSessionState` returns null, and
 *  `status: 'superseded'`, which is set directly by `getSessionState` after
 *  comparing the caller's instance id to the stored one. */
export type SessionStateResponse = Exclude<
  FreebuffSessionServerResponse,
  { status: 'none' } | { status: 'superseded' }
>

export interface InternalSessionRow {
  user_id: string
  status: FreeSessionStatus
  active_instance_id: string
  /** Freebuff model id this row is queued for (or locked to, once active). */
  model: string
  queued_at: Date
  admitted_at: Date | null
  expires_at: Date | null
  created_at: Date
  updated_at: Date
}
